"""Add missing columns to training_data table

Revision ID: 33c655a2a112
Revises: 66e5daa36086
Create Date: 2025-08-20 14:01:02.739548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c655a2a112'
down_revision = '66e5daa36086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('processing_status')
        batch_op.drop_column('processing_error')

    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.alter_column('ad_box_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.add_column(sa.Column('region_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('training_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.drop_column('training_source')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('y')
        batch_op.drop_column('x')
        batch_op.drop_column('page_number')
        batch_op.drop_column('pdf_path')
        batch_op.drop_column('region_type')
        batch_op.alter_column('ad_box_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_error', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('processing_status', sa.VARCHAR(length=50), server_default=sa.text('("uploaded")'), nullable=True))

    # ### end Alembic commands ###
