"""Add detected_automatically column to ad_box table

Revision ID: 66e5daa36086
Revises: 9c4a28edd193
Create Date: 2025-08-17 14:45:14.592376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e5daa36086'
down_revision = '9c4a28edd193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_automatically', sa.Boolean(), default=False))
        
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('processing_status')
        batch_op.drop_column('processing_error')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_error', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('processing_status', sa.VARCHAR(length=50), server_default=sa.text('("uploaded")'), nullable=True))
        
    with op.batch_alter_table('ad_box', schema=None) as batch_op:
        batch_op.drop_column('detected_automatically')

    # ### end Alembic commands ###
