"""Add training data columns for PostgreSQL

Revision ID: 73ee500dc66c
Revises: 66e5daa36086
Create Date: 2025-08-20 14:55:17.019659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ee500dc66c'
down_revision = '66e5daa36086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_publication')
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('processing_status')
        batch_op.drop_column('processing_error')

    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.alter_column('ad_box_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.add_column(sa.Column('region_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('training_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.alter_column('ad_box_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_error', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('processing_status', sa.VARCHAR(length=50), server_default=sa.text('("uploaded")'), nullable=True))

    op.create_table('_alembic_tmp_publication',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('publication_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('total_pages', sa.INTEGER(), nullable=False),
    sa.Column('total_inches', sa.FLOAT(), nullable=False),
    sa.Column('total_ad_inches', sa.FLOAT(), nullable=True),
    sa.Column('ad_percentage', sa.FLOAT(), nullable=True),
    sa.Column('upload_date', sa.DATETIME(), nullable=True),
    sa.Column('processed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
