"""Initial migration with all tables

Revision ID: c9f90144e87f
Revises: 
Create Date: 2025-07-31 14:00:05.752029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f90144e87f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_width_inches', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pdf_height_inches', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pixels_per_inch', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calibration_accurate', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('calibration_accurate')
        batch_op.drop_column('pixels_per_inch')
        batch_op.drop_column('pdf_height_inches')
        batch_op.drop_column('pdf_width_inches')

    # ### end Alembic commands ###
